### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by CucumberSandwich** [MatthewWolff/TwitterScraper#1]
I don't believe twitter allows you to search through a specific user anymore. All the searches yield 0 results.

**Comment by MatthewWolff** [comment]
I jumped to the `form_url` method in `scrape.py` and manually formed a search url and it worked for me. When I tried it on myself (private twitter account) I got 0 results, despite having tweeted recently. However, when searching for a public user, it worked. Try the below url as an example—does it give you results?

https://twitter.com/search?f=tweets&vertical=default&q=from%3Apotus44

**Comment by CucumberSandwich** [comment]
That URL works for me but this doesn't, and the account isn't private. I don't know if any other settings can be set to avoid searches though.

https://twitter.com/search?f=tweets&vertical=default&q=from%3Arusthackreport

**Comment by MatthewWolff** [comment]
error does not appear to be based in the scraper
