### ISSUE TITLE
Change into scraper following list and their respective followers

### ISSUE THREAD

**Issue by Karakor23** [MatthewWolff/TwitterScraper#15]
Due to bots, a CSV would be nice who is following the account

**Comment by MatthewWolff** [comment]
Could you elaborate on what you're asking? You want a function that queries the following and followers lists?

Please provide some example behavior to illustrate what you're  talking about

**Comment by Karakor23** [comment]
Yes, for instance an account that has 10 followings and 1000 followers.
Instead of manually going through the list, and see which accounts are following a certain account...you instead scrape the followers with their data and use the csv for analyzing it

**Comment by MatthewWolff** [comment]
Ah, I see. That's outside the scope of what this scraping package is intended to handle—you would simply use the API to query someone's following list and then use the this scraper for each.

Closing this issue as the requested feature is out of intended scope
