### ISSUE TITLE
Any reason you do it month-by-month?

### ISSUE THREAD

**Issue by panhartstuff** [MatthewWolff/TwitterScraper#2]
Are there any advantages to doing it month-by-month? Is this to bypass certain scrolling limits in Twitter search? I heard that there's something like that, but I have not experienced it myself.

**Comment by MatthewWolff** [comment]
No strong reason. The timeframe selected was just for ease of testing (i was testing on an account with sparse tweets). For accounts with many tweets, I would recommend smaller steps and longer delays so no tweets fail to get processed. The delay part is most important

**Comment by MatthewWolff** [comment]
Just did a total re-write. To answer your question again, I actually didn't do it month by month. The default was day by day. I've changed this to now go at 2 week intervals (14 days). 

The worst-case time for execution of the script is `delay * ( [age of twitter account] / by )`. The larger `--by` is, the quicker it will run. The larger `--delay` is, the slower (but with more certainty that no tweets failed to load).
