### ISSUE TITLE
TypeError: get_user() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by philipjohn** [MatthewWolff/TwitterScraper#9]
After a fresh `git pull` I'm seeing this error when trying to run the scraper, including with the example in the Readme:

> ./scrape.py -u phillipcompeau --by 14 --since 2018-01-01 --until 2019-01-01 
> Traceback (most recent call last):
>   File "/home/philipjohn/projects/TwitterScraper/./scrape.py", line 81, in __check_if_scrapable
>     u = self.api.get_user(self.handle)
>   File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.8/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
>     return method(*args, **kwargs)
> TypeError: get_user() takes 1 positional argument but 2 were given

My python version is 3.9.8 and here's the `pip3 freeze` output for the depencies:

> beautifulsoup4==4.10.0
> requests==2.27.1
> requests-oauthlib==1.3.0
> selenium==4.1.0
> tweepy==4.4.0

This also appears below the error:

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "/home/philipjohn/projects/TwitterScraper/./scrape.py", line 284, in <module>
>     user.scrape(begin, end, args.by, args.delay)
>   File "/home/philipjohn/projects/TwitterScraper/./scrape.py", line 95, in scrape
>     self.__check_if_scrapable()
>   File "/home/philipjohn/projects/TwitterScraper/./scrape.py", line 84, in __check_if_scrapable
>     except tweepy.TweepError as e:
> AttributeError: module 'tweepy' has no attribute 'TweepError'

Perhaps there were some breaking changes in Tweepy ?

**Comment by MatthewWolff** [comment]
This issue was due to using Tweepy v4

the get_user() field takes no positional arguments in v4. Therefore, you must provide a keyword argument. 

the fix here was to change 
api.get_user(handle)

to

api.get_user(screen_name=handle)

I've corrected this in my latest revisions, which now use the most up to date versions of all dependencies

**Comment by philipjohn** [comment]
Thanks @MatthewWolff !
